service: hello

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi: GET /
  register:
    handler: src/route/registerCard.handler
    events:
      - httpApi: POST /register-card
  getCard:
    handler: src/route/cardToken.handler
    events:
      - httpApi: GET /get-card

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-jest-plugin
